/* eslint-disable */
// @ts-nocheck
import {reactive,ref} from "vue";
import { ElTable } from 'element-plus'
export default function useTable(tableRef:ElTable) {

    const tableData = ref([
        {
            "orderId": "1788035271851614209",
            "orderNo": "SO100024735",
            "merchantId": "1787646701184163842",
            "channelId": 0,
            "channelName": "",
            "dataChannel": "",
            "status": "Shipped",
            "orderDate": 1715135803000,
            "purchaseOrderNo": "",
            "referenceNo": "116",
            "buyerFirstName": "",
            "buyerLastName": "",
            "carrier": {
                "name": "DHL",
                "scac": "DHL"
            },
            "freightTerm": "",
            "shipMethod": "",
            "loadDate": null,
            "shippingService": "GND",
            "warehouseId": null,
            "postDate": null,
            "requiredShippingDate": null,
            "channelSalesOrderNumber": "116",
            "deliveryService": "",
            "shipToAddress": {
                "name": "verify",
                "email": "test@test.com",
                "address1": "Calaveras",
                "address2": "",
                "address3": "",
                "phone": "1111111111",
                "city": "Los Angeles",
                "state": "CA",
                "zipCode": "91744",
                "country": "US"
            },
            "billToAddress": {
                "name": "verify",
                "email": "test@test.com",
                "address1": "Calaveras",
                "address2": "",
                "address3": "",
                "phone": "1111111111",
                "city": "Los Angeles",
                "state": "CA",
                "zipCode": "95221",
                "country": "US"
            },
            "itemLines": null,
            "orderNoteList": null,
            "totalAmount": 0,
            "subtotalAmount": 0,
            "discountAmount": 0,
            "salesTaxAmount": null,
            "shippingAmount": null,
            "taxRate": null,
            "tenantId": "1770647137908523009",
            "shipmentList": null,
            "source": "Created",
            "orderAndStatus": "1788035271851614209,SO100024735,Shipped",
            "orderDispatchList": null,
            "createTime": 1715135804000,
            "updateTime": 1715135804000,
            "creator": "1770647138306981890",
            "updater": "1770647138306981890",
            "shipDate": 1716261152000,
            "ruleCode": null,
            "orderAttachData": null,
            "reserve1": null,
            "shipFromAddress": null,
            "automaticShipping": null,
            "itemSku": "3A-2"
        },
        {
            "orderId": "1788035270190669825",
            "orderNo": "SO100024734",
            "merchantId": "1787646701184163842",
            "channelId": 0,
            "channelName": "",
            "dataChannel": "",
            "status": "Shipped",
            "orderDate": 1715135803000,
            "purchaseOrderNo": "",
            "referenceNo": "115",
            "buyerFirstName": "",
            "buyerLastName": "",
            "carrier": {
                "name": null,
                "scac": null
            },
            "freightTerm": "",
            "shipMethod": "",
            "loadDate": null,
            "shippingService": "1 DAY",
            "warehouseId": null,
            "postDate": null,
            "requiredShippingDate": null,
            "channelSalesOrderNumber": "115",
            "deliveryService": "",
            "shipToAddress": {
                "name": "verify",
                "email": "test@test.com",
                "address1": "Calaveras",
                "address2": "",
                "address3": "",
                "phone": "1111111111",
                "city": "Los Angeles",
                "state": "CA",
                "zipCode": "91744",
                "country": "US"
            },
            "billToAddress": {
                "name": "verify",
                "email": "test@test.com",
                "address1": "Calaveras",
                "address2": "",
                "address3": "",
                "phone": "1111111111",
                "city": "Los Angeles",
                "state": "CA",
                "zipCode": "95221",
                "country": "US"
            },
            "itemLines": null,
            "orderNoteList": null,
            "totalAmount": 0,
            "subtotalAmount": 0,
            "discountAmount": 0,
            "salesTaxAmount": null,
            "shippingAmount": null,
            "taxRate": null,
            "tenantId": "1770647137908523009",
            "shipmentList": null,
            "source": "Created",
            "orderAndStatus": "1788035270190669825,SO100024734,Shipped",
            "orderDispatchList": null,
            "createTime": 1715135803000,
            "updateTime": 1719197250000,
            "creator": "1770647138306981890",
            "updater": "1770647138306981890",
            "shipDate": 1719197367000,
            "ruleCode": null,
            "orderAttachData": null,
            "reserve1": null,
            "shipFromAddress": null,
            "automaticShipping": null,
            "itemSku": "3A-2"
        },
        {
            "orderId": "1788035265090396161",
            "orderNo": "SO100024731",
            "merchantId": "1787646701184163842",
            "channelId": 0,
            "channelName": "",
            "dataChannel": "",
            "status": "New",
            "orderDate": 1715135802000,
            "purchaseOrderNo": "",
            "referenceNo": "112",
            "buyerFirstName": "",
            "buyerLastName": "",
            "carrier": {
                "name": "USPS",
                "scac": "USPS"
            },
            "freightTerm": "",
            "shipMethod": "",
            "loadDate": null,
            "shippingService": "1 DAY",
            "warehouseId": null,
            "postDate": null,
            "requiredShippingDate": null,
            "channelSalesOrderNumber": "112",
            "deliveryService": "",
            "shipToAddress": {
                "name": "verify",
                "email": "test@test.com",
                "address1": "Calaveras",
                "address2": "",
                "address3": "",
                "phone": "1111111111",
                "city": "Los Angeles",
                "state": "CA",
                "zipCode": "91744",
                "country": "US"
            },
            "billToAddress": {
                "name": "verify",
                "email": "test@test.com",
                "address1": "Calaveras",
                "address2": "",
                "address3": "",
                "phone": "1111111111",
                "city": "Los Angeles",
                "state": "CA",
                "zipCode": "95221",
                "country": "US"
            },
            "itemLines": null,
            "orderNoteList": null,
            "totalAmount": 0,
            "subtotalAmount": 0,
            "discountAmount": 0,
            "salesTaxAmount": null,
            "shippingAmount": null,
            "taxRate": null,
            "tenantId": "1770647137908523009",
            "shipmentList": null,
            "source": "Created",
            "orderAndStatus": "1788035265090396161,SO100024731,New",
            "orderDispatchList": null,
            "createTime": 1715135802000,
            "updateTime": 1719214006000,
            "creator": "1770647138306981890",
            "updater": "1770647138306981890",
            "shipDate": null,
            "ruleCode": null,
            "orderAttachData": null,
            "reserve1": null,
            "shipFromAddress": null,
            "automaticShipping": null,
            "itemSku": "3A-2"
        },
        {
            "orderId": "1788035266738757633",
            "orderNo": "SO100024732",
            "merchantId": "1787646701184163842",
            "channelId": 0,
            "channelName": "",
            "dataChannel": "",
            "status": "New",
            "orderDate": 1715135802000,
            "purchaseOrderNo": "",
            "referenceNo": "113",
            "buyerFirstName": "",
            "buyerLastName": "",
            "carrier": {
                "name": "",
                "scac": ""
            },
            "freightTerm": "",
            "shipMethod": "",
            "loadDate": null,
            "shippingService": "",
            "warehouseId": null,
            "postDate": null,
            "requiredShippingDate": null,
            "channelSalesOrderNumber": "113",
            "deliveryService": "",
            "shipToAddress": {
                "name": "verify",
                "email": "test@test.com",
                "address1": "Calaveras",
                "address2": "",
                "address3": "",
                "phone": "1111111111",
                "city": "Los Angeles",
                "state": "CA",
                "zipCode": "91744",
                "country": "US"
            },
            "billToAddress": {
                "name": "verify",
                "email": "test@test.com",
                "address1": "Calaveras",
                "address2": "",
                "address3": "",
                "phone": "1111111111",
                "city": "Los Angeles",
                "state": "CA",
                "zipCode": "95221",
                "country": "US"
            },
            "itemLines": null,
            "orderNoteList": null,
            "totalAmount": 0,
            "subtotalAmount": 0,
            "discountAmount": 0,
            "salesTaxAmount": null,
            "shippingAmount": null,
            "taxRate": null,
            "tenantId": "1770647137908523009",
            "shipmentList": null,
            "source": "Created",
            "orderAndStatus": "1788035266738757633,SO100024732,New",
            "orderDispatchList": null,
            "createTime": 1715135802000,
            "updateTime": 1715135802000,
            "creator": "1770647138306981890",
            "updater": "1770647138306981890",
            "shipDate": null,
            "ruleCode": null,
            "orderAttachData": null,
            "reserve1": null,
            "shipFromAddress": null,
            "automaticShipping": null,
            "itemSku": "3A-2"
        },
        {
            "orderId": "1788035268710080514",
            "orderNo": "SO100024733",
            "merchantId": "1787646701184163842",
            "channelId": 0,
            "channelName": "",
            "dataChannel": "",
            "status": "New",
            "orderDate": 1715135802000,
            "purchaseOrderNo": "",
            "referenceNo": "114",
            "buyerFirstName": "",
            "buyerLastName": "",
            "carrier": {
                "name": "",
                "scac": ""
            },
            "freightTerm": "",
            "shipMethod": "",
            "loadDate": null,
            "shippingService": "",
            "warehouseId": null,
            "postDate": null,
            "requiredShippingDate": null,
            "channelSalesOrderNumber": "114",
            "deliveryService": "",
            "shipToAddress": {
                "name": "verify",
                "email": "test@test.com",
                "address1": "Calaveras",
                "address2": "",
                "address3": "",
                "phone": "1111111111",
                "city": "Los Angeles",
                "state": "CA",
                "zipCode": "91744",
                "country": "US"
            },
            "billToAddress": {
                "name": "verify",
                "email": "test@test.com",
                "address1": "Calaveras",
                "address2": "",
                "address3": "",
                "phone": "1111111111",
                "city": "Los Angeles",
                "state": "CA",
                "zipCode": "95221",
                "country": "US"
            },
            "itemLines": null,
            "orderNoteList": null,
            "totalAmount": 0,
            "subtotalAmount": 0,
            "discountAmount": 0,
            "salesTaxAmount": null,
            "shippingAmount": null,
            "taxRate": null,
            "tenantId": "1770647137908523009",
            "shipmentList": null,
            "source": "Created",
            "orderAndStatus": "1788035268710080514,SO100024733,New",
            "orderDispatchList": null,
            "createTime": 1715135803000,
            "updateTime": 1715135803000,
            "creator": "1770647138306981890",
            "updater": "1770647138306981890",
            "shipDate": null,
            "ruleCode": null,
            "orderAttachData": null,
            "reserve1": null,
            "shipFromAddress": null,
            "automaticShipping": null,
            "itemSku": "3A-2"
        },
        {
            "orderId": "1788035263655944194",
            "orderNo": "SO100024730",
            "merchantId": "1787646701184163842",
            "channelId": 0,
            "channelName": "",
            "dataChannel": "",
            "status": "New",
            "orderDate": 1715135801000,
            "purchaseOrderNo": "",
            "referenceNo": "111",
            "buyerFirstName": "",
            "buyerLastName": "",
            "carrier": {
                "name": "",
                "scac": ""
            },
            "freightTerm": "",
            "shipMethod": "",
            "loadDate": null,
            "shippingService": "",
            "warehouseId": null,
            "postDate": null,
            "requiredShippingDate": null,
            "channelSalesOrderNumber": "111",
            "deliveryService": "",
            "shipToAddress": {
                "name": "verify",
                "email": "test@test.com",
                "address1": "Calaveras",
                "address2": "",
                "address3": "",
                "phone": "1111111111",
                "city": "Los Angeles",
                "state": "CA",
                "zipCode": "91744",
                "country": "US"
            },
            "billToAddress": {
                "name": "verify",
                "email": "test@test.com",
                "address1": "Calaveras",
                "address2": "",
                "address3": "",
                "phone": "1111111111",
                "city": "Los Angeles",
                "state": "CA",
                "zipCode": "95221",
                "country": "US"
            },
            "itemLines": null,
            "orderNoteList": null,
            "totalAmount": 0,
            "subtotalAmount": 0,
            "discountAmount": 0,
            "salesTaxAmount": null,
            "shippingAmount": null,
            "taxRate": null,
            "tenantId": "1770647137908523009",
            "shipmentList": null,
            "source": "Created",
            "orderAndStatus": "1788035263655944194,SO100024730,New",
            "orderDispatchList": null,
            "createTime": 1715135802000,
            "updateTime": 1715135802000,
            "creator": "1770647138306981890",
            "updater": "1770647138306981890",
            "shipDate": null,
            "ruleCode": null,
            "orderAttachData": null,
            "reserve1": null,
            "shipFromAddress": null,
            "automaticShipping": null,
            "itemSku": "3A-2"
        },
        {
            "orderId": "1788035262183743490",
            "orderNo": "SO100024729",
            "merchantId": "1787646701184163842",
            "channelId": 0,
            "channelName": "",
            "dataChannel": "",
            "status": "New",
            "orderDate": 1715135801000,
            "purchaseOrderNo": "",
            "referenceNo": "110",
            "buyerFirstName": "",
            "buyerLastName": "",
            "carrier": {
                "name": "",
                "scac": ""
            },
            "freightTerm": "",
            "shipMethod": "",
            "loadDate": null,
            "shippingService": "",
            "warehouseId": null,
            "postDate": null,
            "requiredShippingDate": null,
            "channelSalesOrderNumber": "110",
            "deliveryService": "",
            "shipToAddress": {
                "name": "verify",
                "email": "test@test.com",
                "address1": "Calaveras",
                "address2": "",
                "address3": "",
                "phone": "1111111111",
                "city": "Los Angeles",
                "state": "CA",
                "zipCode": "91744",
                "country": "US"
            },
            "billToAddress": {
                "name": "verify",
                "email": "test@test.com",
                "address1": "Calaveras",
                "address2": "",
                "address3": "",
                "phone": "1111111111",
                "city": "Los Angeles",
                "state": "CA",
                "zipCode": "95221",
                "country": "US"
            },
            "itemLines": null,
            "orderNoteList": null,
            "totalAmount": 0,
            "subtotalAmount": 0,
            "discountAmount": 0,
            "salesTaxAmount": null,
            "shippingAmount": null,
            "taxRate": null,
            "tenantId": "1770647137908523009",
            "shipmentList": null,
            "source": "Created",
            "orderAndStatus": "1788035262183743490,SO100024729,New",
            "orderDispatchList": null,
            "createTime": 1715135801000,
            "updateTime": 1715135801000,
            "creator": "1770647138306981890",
            "updater": "1770647138306981890",
            "shipDate": null,
            "ruleCode": null,
            "orderAttachData": null,
            "reserve1": null,
            "shipFromAddress": null,
            "automaticShipping": null,
            "itemSku": "3A-2"
        },
        {
            "orderId": "1788035260543770626",
            "orderNo": "SO100024728",
            "merchantId": "1787646701184163842",
            "channelId": 0,
            "channelName": "",
            "dataChannel": "",
            "status": "New",
            "orderDate": 1715135801000,
            "purchaseOrderNo": "",
            "referenceNo": "109",
            "buyerFirstName": "",
            "buyerLastName": "",
            "carrier": {
                "name": "",
                "scac": ""
            },
            "freightTerm": "",
            "shipMethod": "",
            "loadDate": null,
            "shippingService": "",
            "warehouseId": null,
            "postDate": null,
            "requiredShippingDate": null,
            "channelSalesOrderNumber": "109",
            "deliveryService": "",
            "shipToAddress": {
                "name": "verify",
                "email": "test@test.com",
                "address1": "Calaveras",
                "address2": "",
                "address3": "",
                "phone": "1111111111",
                "city": "Los Angeles",
                "state": "CA",
                "zipCode": "91744",
                "country": "US"
            },
            "billToAddress": {
                "name": "verify",
                "email": "test@test.com",
                "address1": "Calaveras",
                "address2": "",
                "address3": "",
                "phone": "1111111111",
                "city": "Los Angeles",
                "state": "CA",
                "zipCode": "95221",
                "country": "US"
            },
            "itemLines": null,
            "orderNoteList": null,
            "totalAmount": 0,
            "subtotalAmount": 0,
            "discountAmount": 0,
            "salesTaxAmount": null,
            "shippingAmount": null,
            "taxRate": null,
            "tenantId": "1770647137908523009",
            "shipmentList": null,
            "source": "Created",
            "orderAndStatus": "1788035260543770626,SO100024728,New",
            "orderDispatchList": null,
            "createTime": 1715135801000,
            "updateTime": 1715135801000,
            "creator": "1770647138306981890",
            "updater": "1770647138306981890",
            "shipDate": null,
            "ruleCode": null,
            "orderAttachData": null,
            "reserve1": null,
            "shipFromAddress": null,
            "automaticShipping": null,
            "itemSku": "3A-2"
        },
        {
            "orderId": "1788035259017043969",
            "orderNo": "SO100024727",
            "merchantId": "1787646701184163842",
            "channelId": 0,
            "channelName": "",
            "dataChannel": "",
            "status": "New",
            "orderDate": 1715135800000,
            "purchaseOrderNo": "",
            "referenceNo": "108",
            "buyerFirstName": "",
            "buyerLastName": "",
            "carrier": {
                "name": "",
                "scac": ""
            },
            "freightTerm": "",
            "shipMethod": "",
            "loadDate": null,
            "shippingService": "",
            "warehouseId": null,
            "postDate": null,
            "requiredShippingDate": null,
            "channelSalesOrderNumber": "108",
            "deliveryService": "",
            "shipToAddress": {
                "name": "verify",
                "email": "test@test.com",
                "address1": "Calaveras",
                "address2": "",
                "address3": "",
                "phone": "1111111111",
                "city": "Los Angeles",
                "state": "CA",
                "zipCode": "91744",
                "country": "US"
            },
            "billToAddress": {
                "name": "verify",
                "email": "test@test.com",
                "address1": "Calaveras",
                "address2": "",
                "address3": "",
                "phone": "1111111111",
                "city": "Los Angeles",
                "state": "CA",
                "zipCode": "95221",
                "country": "US"
            },
            "itemLines": null,
            "orderNoteList": null,
            "totalAmount": 0,
            "subtotalAmount": 0,
            "discountAmount": 0,
            "salesTaxAmount": null,
            "shippingAmount": null,
            "taxRate": null,
            "tenantId": "1770647137908523009",
            "shipmentList": null,
            "source": "Created",
            "orderAndStatus": "1788035259017043969,SO100024727,New",
            "orderDispatchList": null,
            "createTime": 1715135800000,
            "updateTime": 1715135800000,
            "creator": "1770647138306981890",
            "updater": "1770647138306981890",
            "shipDate": null,
            "ruleCode": null,
            "orderAttachData": null,
            "reserve1": null,
            "shipFromAddress": null,
            "automaticShipping": null,
            "itemSku": "3A-2"
        },
        {
            "orderId": "1788035257276407809",
            "orderNo": "SO100024726",
            "merchantId": "1787646701184163842",
            "channelId": 0,
            "channelName": "",
            "dataChannel": "",
            "status": "New",
            "orderDate": 1715135800000,
            "purchaseOrderNo": "",
            "referenceNo": "107",
            "buyerFirstName": "",
            "buyerLastName": "",
            "carrier": {
                "name": "",
                "scac": ""
            },
            "freightTerm": "",
            "shipMethod": "",
            "loadDate": null,
            "shippingService": "",
            "warehouseId": null,
            "postDate": null,
            "requiredShippingDate": null,
            "channelSalesOrderNumber": "107",
            "deliveryService": "",
            "shipToAddress": {
                "name": "verify",
                "email": "test@test.com",
                "address1": "Calaveras",
                "address2": "",
                "address3": "",
                "phone": "1111111111",
                "city": "Los Angeles",
                "state": "CA",
                "zipCode": "91744",
                "country": "US"
            },
            "billToAddress": {
                "name": "verify",
                "email": "test@test.com",
                "address1": "Calaveras",
                "address2": "",
                "address3": "",
                "phone": "1111111111",
                "city": "Los Angeles",
                "state": "CA",
                "zipCode": "95221",
                "country": "US"
            },
            "itemLines": null,
            "orderNoteList": null,
            "totalAmount": 0,
            "subtotalAmount": 0,
            "discountAmount": 0,
            "salesTaxAmount": null,
            "shippingAmount": null,
            "taxRate": null,
            "tenantId": "1770647137908523009",
            "shipmentList": null,
            "source": "Created",
            "orderAndStatus": "1788035257276407809,SO100024726,New",
            "orderDispatchList": null,
            "createTime": 1715135800000,
            "updateTime": 1715135800000,
            "creator": "1770647138306981890",
            "updater": "1770647138306981890",
            "shipDate": null,
            "ruleCode": null,
            "orderAttachData": null,
            "reserve1": null,
            "shipFromAddress": null,
            "automaticShipping": null,
            "itemSku": "3A-2"
        }
    ])

    const columns = reactive([
        {
            dataIndex: 'dataChannel',
            title: 'CHANNEL',
            width: 150,
        },
        {
            dataIndex: 'channelName',
            title: 'CHANNEL NAME',
            width: 150
        },
        {
            dataIndex: 'orderNo',
            slotName: 'orderIdUrl',
            title: 'ORDER NO',
            width: 150,
            sortable: true
        },
        {
            dataIndex: 'channelSalesOrderNumber',
            title: 'CHANNEL SALES ORDER NO',
            width: 180,
            sortable: true
        },
        {
            dataIndex: 'status',
            slotName: 'statusName',
            width: 173,
            title: 'STATUS'
        },
        {
            dataIndex: 'shipToAddress.name',
            title: 'RECIPIENT',
            width: 180,
        },
        {
            dataIndex: 'shipToAddress.country',
            title: 'COUNTRY',
            width: 180,
        },
        {
            dataIndex: 'purchaseOrderNo',
            title: 'PO NO',
            width: 173
        },
        {
            dataIndex: 'referenceNo',
            title: 'REFERENCE',
            width: 173
        },
        {
            dataIndex: 'carrier.name',
            title: 'CARRIER',
            width: 180,
            render: record => {
                if (!isEmpty(record.record.carrier)) {
                    return record.record.carrier.name
                }
                return ''
            }
        },
        {
            dataIndex: 'orderDate',
            title: 'ORDER DATE',
            width: 170,
            render: record => {
                if (!isEmpty(record.record.orderDate)) {
                    return formattedTime12Hour(record.record.orderDate)
                }
                return ''
            },
            sortable: true
        },
        {
            dataIndex: 'totalAmount',
            title: 'TOTAL',
            width: 170,
            render: record => {
                if (!isEmpty(record.record.totalAmount)) {
                    return '$' + record.record.totalAmount
                }
                return ''
            },
            sortable: true
        },
        {
            dataIndex: 'shipDate',
            title: 'SHIPDATE',
            width: 180,
            render: record => {
                if (!isEmpty(record.record.shipDate)) {
                    return formattedTime12Hour(record.record.shipDate)
                }
                return ''
            }
        },
        {
            dataIndex: 'itemSku',
            title: 'PRODUCT',
            width: 180,
            slotName: 'itemSkuSlot'
        }
    ])

    const selection = ref<any[]>([])
    function selectionChange(val: any[]){
        selection.value = val
    }
    const toggleSelection = (rows?: any[]) => {
        if (rows) {
            rows.forEach((row) => {
                tableRef.value!.toggleRowSelection(row, undefined)
            })
        } else {
            tableRef.value!.clearSelection()
        }
    }

    return {
        columns,
        tableData,
        selectionChange,
        toggleSelection,
        selection,
    }
}